# generate_csdi_two_stage_sines.py
# ------------------------------------------------------------
# Two-stage missingness Synthetic Sines dataset in CSDI dataloader .pkl format
#
# Stage 0: latent full series X_latent generated by Appendix D.1 + Table 6/7:
#   x_k(t) = sum_{i=1..Nk} a_{k,i} sin(2π f_{k,i} t + φ_{k,i}) + ε_k
#   f_{k,i} ~ Beta(2,2)*w_{k,i} + (mu_{k,i} - w_{k,i}/2)
#   φ_{k,i} ~ Uniform(0, 2π)
#   ε_k ~ N(0, σ_k^2)   (σ_k default 0.1 for all channels; paper doesn't specify numeric)
#
# Stage 1 (BASE missing): fixed 10% random missing across the whole dataset
#   base_mask: 1=available, 0=missing (intrinsic unavailability, NOT evaluated)
#
# Stage 2 (TASK missing): on top of base, apply missing mode (MCAR/Sequence/Block) and ratio r in {10,50,90}
#   task_mask: 1=keep, 0=hide (to be imputed/evaluated if base_mask=1)
#
# For CSDI-style records:
#   observed_mask = base_mask & task_mask
#   gt_mask       = base_mask
#   observed_data = X_latent with observed_mask==0 set to 0
#   X_true        = X_latent  (you asked: "the initial 10% random missing should be kept as imputation truth")
#                 Note: evaluation should only consider positions where gt_mask==1 and observed_mask==0
#
# Output:
#   out_dir/
#     meta.json
#     train.pkl / valid.pkl / test.pkl  (for each setting)
#     e.g. mcar_10/train.pkl, mcar_10/valid.pkl, mcar_10/test.pkl
#          sequence_50/...
#          block_90/...
#
# Each .pkl is list[dict], each dict:
#   timepoints: (L,)
#   observed_data: (L,K)
#   observed_mask: (L,K)
#   gt_mask: (L,K)
#   X_true: (L,K)   # full latent truth (no missing), while gt_mask excludes base missing from eval
#
# Usage:
#   python generate_csdi_two_stage_sines.py --out_dir ./csdi_two_stage --seed 42
#   python generate_csdi_two_stage_sines.py --out_dir ./csdi_two_stage --sigma 0.1 --base_missing 0.10
# ------------------------------------------------------------

import os
import json
import pickle
import argparse
import numpy as np


# -------------------------
# Table 7 specs (from your figure)
# -------------------------
CHANNEL_SPECS = {
    1: dict(Nk=1, mu=[1.0], w=[1.0], a=[1.0]),
    2: dict(Nk=2, mu=[1.0, 2.0], w=[1.0, 1.5], a=[0.5, 1.0]),
    3: dict(Nk=3, mu=[1.0, 2.0, 3.0], w=[1.0, 1.0, 1.5], a=[0.5, 1.0, 1.5]),
    4: dict(Nk=4, mu=[0.5, 1.0, 1.5, 2.0], w=[1.0, 1.0, 1.0, 2.0], a=[0.8, 1.2, 1.5, 2.0]),
    5: dict(Nk=5, mu=[0.5, 1.0, 2.0, 3.0, 4.0], w=[0.5, 1.0, 1.0, 1.5, 2.0], a=[1.0, 1.5, 2.0, 2.5, 3.0]),
}


# -------------------------
# Stage 0: latent generation
# -------------------------
def sample_frequencies_beta(mu, w, rng, alpha=2.0, beta=2.0):
    """f ~ Beta(2,2)*w + (mu - w/2)"""
    mu = np.asarray(mu, dtype=np.float64)
    w = np.asarray(w, dtype=np.float64)
    z = rng.beta(alpha, beta, size=mu.shape)
    return z * w + (mu - 0.5 * w)


def generate_latent_series(
    N: int,
    L: int,
    K: int,
    T: float,
    seed: int,
    sigma_per_channel,
    phase_mode: str = "uniform",
):
    assert K == 5, "This generator follows Table 6/7 (K=5)."
    rng = np.random.default_rng(seed)
    t = np.linspace(0.0, T, L, endpoint=False, dtype=np.float64)  # (L,)

    sigma_per_channel = np.asarray(sigma_per_channel, dtype=np.float64)
    if sigma_per_channel.shape != (K,):
        raise ValueError(f"sigma_per_channel must have shape ({K},), got {sigma_per_channel.shape}")

    X = np.zeros((N, L, K), dtype=np.float64)

    for n in range(N):
        for k in range(1, K + 1):
            spec = CHANNEL_SPECS[k]
            Nk = int(spec["Nk"])
            a = np.asarray(spec["a"], dtype=np.float64)
            mu = spec["mu"]
            w = spec["w"]

            f = sample_frequencies_beta(mu, w, rng)
            if phase_mode == "uniform":
                phi = rng.uniform(0.0, 2.0 * np.pi, size=(Nk,))
            else:
                raise ValueError(f"Unknown phase_mode: {phase_mode}")

            y = np.zeros((L,), dtype=np.float64)
            for i in range(Nk):
                y += a[i] * np.sin(2.0 * np.pi * f[i] * t + phi[i])

            X[n, :, k - 1] = y

    # Additive Gaussian noise per channel
    noise = rng.normal(0.0, 1.0, size=X.shape) * sigma_per_channel.reshape(1, 1, K)
    X = X + noise
    return t, X


# -------------------------
# Stage 1: base random missing (fixed 10%)
# mask convention: 1=available, 0=missing
# -------------------------
def random_mask(shape, missing_rate, rng):
    return (rng.random(shape) >= missing_rate).astype(np.uint8)


# -------------------------
# Stage 2: task missing masks (mode + ratio)
# task_mask convention: 1=keep, 0=hide
# -------------------------
def task_mask_mcar(N, L, K, missing_rate, rng):
    return random_mask((N, L, K), missing_rate, rng)


def task_mask_sequence(N, L, K, missing_rate, rng):
    """
    For each (n,k), hide one contiguous segment whose length ≈ missing_rate*L.
    """
    seg_len = int(round(missing_rate * L))
    seg_len = max(1, min(L, seg_len))
    mask = np.ones((N, L, K), dtype=np.uint8)
    for n in range(N):
        for k in range(K):
            start = int(rng.integers(0, L - seg_len + 1))
            mask[n, start:start + seg_len, k] = 0
    return mask


def task_mask_block(N, L, K, missing_rate, rng, max_tries=20000):
    """
    For each sample, hide rectangles in the (time, channel) plane.
    Ensures exact per-sample hidden count close to missing_rate * L * K.
    """
    target = int(round(missing_rate * L * K))
    target = max(1, min(L * K, target))
    mask = np.ones((N, L, K), dtype=np.uint8)

    for n in range(N):
        miss = np.zeros((L, K), dtype=bool)
        cur = 0
        tries = 0
        while cur < target and tries < max_tries:
            tries += 1
            t_len = int(rng.integers(low=5, high=min(40, L) + 1))
            k_len = int(rng.integers(low=1, high=min(3, K) + 1))
            t0 = int(rng.integers(0, L - t_len + 1))
            k0 = int(rng.integers(0, K - k_len + 1))

            block = np.zeros_like(miss)
            block[t0:t0 + t_len, k0:k0 + k_len] = True
            new = block & (~miss)
            add = int(new.sum())
            if add == 0:
                continue
            if cur + add > target and add > 1:
                continue
            miss |= new
            cur += add

        if cur < target:
            candidates = np.argwhere(~miss)
            need = target - cur
            idx = rng.choice(len(candidates), size=need, replace=False)
            pts = candidates[idx]
            miss[pts[:, 0], pts[:, 1]] = True

        for k in range(K):
            mask[n, :, k][miss[:, k]] = 0

    return mask


# -------------------------
# Build CSDI records
# observed_mask = base_mask & task_mask
# gt_mask       = base_mask
# observed_data = X_true with observed_mask==0 set to 0
# X_true        = X_true full latent (no missing)
# -------------------------
def build_csdi_records(t, X_true, base_mask, task_mask):
    obs_mask = (base_mask & task_mask).astype(np.uint8)  # (N,L,K)
    gt_mask = base_mask.astype(np.uint8)

    X_obs = X_true.copy()
    X_obs[obs_mask == 0] = 0.0

    t32 = t.astype(np.float32)
    obs_mask_f = obs_mask.astype(np.float32)
    gt_mask_f = gt_mask.astype(np.float32)

    records = []
    N = X_true.shape[0]
    for n in range(N):
        records.append({
            "timepoints": t32,                      # (L,)
            "observed_data": X_obs[n].astype(np.float32),     # (L,K)
            "observed_mask": obs_mask_f[n],         # (L,K)
            "gt_mask": gt_mask_f[n],                # (L,K)
            "X_true": X_true[n].astype(np.float32), # (L,K)
        })
    return records


def save_pkl(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        pickle.dump(obj, f, protocol=pickle.HIGHEST_PROTOCOL)


def compute_missing_rate(mask_u8):
    # mask is 1=keep,0=hide
    return 1.0 - float(mask_u8.mean())


def main():
    parser = argparse.ArgumentParser()

    # Output / seed
    parser.add_argument("--out_dir", type=str, default="./data/sines")
    parser.add_argument("--seed", type=int, default=42)

    # Dataset size (Table 6 defaults)
    parser.add_argument("--n_samples", type=int, default=2000)
    parser.add_argument("--K", type=int, default=5)
    parser.add_argument("--L", type=int, default=100)
    parser.add_argument("--T", type=float, default=10.0)

    # Noise
    parser.add_argument("--sigma", type=float, default=0.10, help="σ_k (same for all channels).")
    parser.add_argument("--phase_mode", type=str, default="uniform", choices=["uniform"])

    # Two-stage missing
    parser.add_argument("--base_missing", type=float, default=0.10,
                        help="Stage-1 base random missing rate (fixed across all settings).")
    parser.add_argument("--ratios", type=str, default="0.10,0.50,0.90",
                        help="Stage-2 task missing ratios, comma-separated.")
    parser.add_argument("--modes", type=str, default="mcar,sequence,block",
                        help="Stage-2 missing modes, comma-separated from {mcar,sequence,block}.")

    # Split
    parser.add_argument("--train_ratio", type=float, default=0.7)
    parser.add_argument("--valid_ratio", type=float, default=0.1)
    parser.add_argument("--test_ratio", type=float, default=0.2)

    args = parser.parse_args()

    if not np.isclose(args.train_ratio + args.valid_ratio + args.test_ratio, 1.0):
        raise ValueError("train_ratio + valid_ratio + test_ratio must sum to 1.0")

    os.makedirs(args.out_dir, exist_ok=True)

    # Parse lists
    ratios = [float(x.strip()) for x in args.ratios.split(",") if x.strip()]
    modes = [x.strip().lower() for x in args.modes.split(",") if x.strip()]
    for m in modes:
        if m not in {"mcar", "sequence", "block"}:
            raise ValueError(f"Unknown mode: {m}")

    # Stage 0: latent full series (this is what we store as X_true)
    sigma_per_channel = [args.sigma] * args.K
    t, X_true = generate_latent_series(
        N=args.n_samples,
        L=args.L,
        K=args.K,
        T=args.T,
        seed=args.seed,
        sigma_per_channel=sigma_per_channel,
        phase_mode=args.phase_mode,
    )

    # Stage 1: base random missing (fixed)
    rng_base = np.random.default_rng(args.seed + 1111)
    base_mask = random_mask(X_true.shape, args.base_missing, rng_base).astype(np.uint8)

    # Split indices (same splits for all settings)
    rng_split = np.random.default_rng(args.seed + 2222)
    idx = np.arange(args.n_samples)
    rng_split.shuffle(idx)

    n_train = int(round(args.train_ratio * args.n_samples))
    n_valid = int(round(args.valid_ratio * args.n_samples))
    n_test = args.n_samples - n_train - n_valid

    train_idx = idx[:n_train]
    valid_idx = idx[n_train:n_train + n_valid]
    test_idx = idx[n_train + n_valid:]
    assert len(test_idx) == n_test

    def take(a, inds):
        return a[inds]

    # Save meta
    meta = {
        "table6": {"n_samples": args.n_samples, "features": args.K, "time_steps": args.L, "time_span_T": args.T,
                   "missing_types": ["MCAR", "Sequence", "Block"], "missing_percents": [10, 50, 90]},
        "table7_channel_specs": CHANNEL_SPECS,
        "noise": {"sigma_per_channel": sigma_per_channel, "phase_mode": args.phase_mode},
        "two_stage_missing": {
            "stage1_base_missing": args.base_missing,
            "stage2_modes": modes,
            "stage2_ratios": ratios,
            "mask_definitions": {
                "base_mask": "1=available,0=missing (intrinsic; excluded from evaluation)",
                "task_mask": "1=keep,0=hide (to be imputed if base_mask=1)",
                "observed_mask": "base_mask & task_mask",
                "gt_mask": "base_mask",
                "evaluation_positions": "gt_mask==1 and observed_mask==0",
            },
        },
        "split": {"train": args.train_ratio, "valid": args.valid_ratio, "test": args.test_ratio},
        "csdi_record_keys": ["timepoints", "observed_data", "observed_mask", "gt_mask", "X_true"],
        "shapes": {"timepoints": "(L,)", "observed_data": "(L,K)", "observed_mask": "(L,K)", "gt_mask": "(L,K)", "X_true": "(L,K)"},
    }
    with open(os.path.join(args.out_dir, "meta.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)

    # Stage 2: generate per (mode, ratio) dataset splits
    for mode in modes:
        for r in ratios:
            rng_task = np.random.default_rng(args.seed + 3333 + int(r * 1000) + hash(mode) % 1000)

            if mode == "mcar":
                task_mask = task_mask_mcar(args.n_samples, args.L, args.K, r, rng_task)
            elif mode == "sequence":
                task_mask = task_mask_sequence(args.n_samples, args.L, args.K, r, rng_task)
            elif mode == "block":
                task_mask = task_mask_block(args.n_samples, args.L, args.K, r, rng_task)
            else:
                raise ValueError(mode)

            # Build records (full), then subset by split
            records = build_csdi_records(t, X_true, base_mask, task_mask)

            # Subset records by indices (avoid copying huge arrays repeatedly)
            train_records = [records[i] for i in train_idx]
            valid_records = [records[i] for i in valid_idx]
            test_records = [records[i] for i in test_idx]

            setting_name = f"{mode}_{int(round(r * 100))}"
            setting_dir = os.path.join(args.out_dir, setting_name)
            os.makedirs(setting_dir, exist_ok=True)

            save_pkl(os.path.join(setting_dir, "train.pkl"), train_records)
            save_pkl(os.path.join(setting_dir, "valid.pkl"), valid_records)
            save_pkl(os.path.join(setting_dir, "test.pkl"), test_records)

            # Quick sanity report
            base_miss = compute_missing_rate(base_mask)
            task_miss = compute_missing_rate(task_mask)
            obs_miss = compute_missing_rate((base_mask & task_mask).astype(np.uint8))
            print(f"[{setting_name}] base_missing={base_miss:.3f}  task_missing={task_miss:.3f}  observed_missing={obs_miss:.3f}")
            print(f"  saved -> {setting_dir}/train.pkl, valid.pkl, test.pkl")

    print(f"\nDone. Root output: {args.out_dir}")
    print("Evaluation positions per sample: (gt_mask==1) & (observed_mask==0)")


if __name__ == "__main__":
    main()
